"""add city, abbreviation, logo_url to teams

Revision ID: 2a9c2cf6fa58
Revises: 44880c28c508
Create Date: 2026-07-02 16:42:49.348158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9c2cf6fa58'
down_revision: Union[str, Sequence[str], None] = '44880c28c508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
