"""add stadium_image_url to teams

Revision ID: 31544980d0bb
Revises: d502126ee310
Create Date: 2026-07-06 20:31:48.915465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31544980d0bb'
down_revision: Union[str, Sequence[str], None] = 'd502126ee310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('stadium_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'stadium_image_url')
    # ### end Alembic commands ###
