"""actually add city, abbreviation, logo_url to teams

Revision ID: 4089d34f0d8c
Revises: 2a9c2cf6fa58
Create Date: 2026-07-02 16:44:09.954193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4089d34f0d8c'
down_revision: Union[str, Sequence[str], None] = '2a9c2cf6fa58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('city', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('abbreviation', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'logo_url')
    op.drop_column('teams', 'abbreviation')
    op.drop_column('teams', 'city')
    # ### end Alembic commands ###
