"""add stadium_name to teams

Revision ID: 40fe846c3013
Revises: 44f324d99baf
Create Date: 2026-07-03 16:03:46.360456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40fe846c3013'
down_revision: Union[str, Sequence[str], None] = '44f324d99baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('stadium_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'stadium_name')
    # ### end Alembic commands ###
