"""add PUT and DELETE endpoints for teams and players

Revision ID: 421400c837d4
Revises: 4089d34f0d8c
Create Date: 2026-07-02 16:52:05.560544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421400c837d4'
down_revision: Union[str, Sequence[str], None] = '4089d34f0d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
