"""add chemistry_type to players

Revision ID: 44880c28c508
Revises: 9dbc4fc1b20b
Create Date: 2026-07-02 15:26:23.407860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44880c28c508'
down_revision: Union[str, Sequence[str], None] = '9dbc4fc1b20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('chemistry_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'chemistry_type')
    # ### end Alembic commands ###
