"""add_player_group_to_players

Revision ID: 97fd064c0446
Revises: 31544980d0bb
Create Date: 2026-08-15 21:54:45.373684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97fd064c0446'
down_revision: Union[str, Sequence[str], None] = '31544980d0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# modified from autogenerated alembic code, column was added manually
def upgrade() -> None:
    pass

def downgrade() -> None:
    op.drop_column('players', 'player_group')
