"""add position and stat fields to players

Revision ID: 9dbc4fc1b20b
Revises: dcd8ba47aef3
Create Date: 2026-07-02 14:45:50.168311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dbc4fc1b20b'
down_revision: Union[str, Sequence[str], None] = 'dcd8ba47aef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('primary_position', sa.String(), nullable=False))
    op.add_column('players', sa.Column('secondary_positions', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('power', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('contact', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('speed', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('fielding', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('arm', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('velocity', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('junk', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('accuracy', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('pitch_arsenal', sa.JSON(), nullable=True))
    op.drop_column('players', 'stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('stats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('players', 'pitch_arsenal')
    op.drop_column('players', 'accuracy')
    op.drop_column('players', 'junk')
    op.drop_column('players', 'velocity')
    op.drop_column('players', 'arm')
    op.drop_column('players', 'fielding')
    op.drop_column('players', 'speed')
    op.drop_column('players', 'contact')
    op.drop_column('players', 'power')
    op.drop_column('players', 'secondary_positions')
    op.drop_column('players', 'primary_position')
    # ### end Alembic commands ###
