"""add rating to players

Revision ID: a869c436d8f0
Revises: f559570bf898
Create Date: 2026-07-06 14:28:55.192484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a869c436d8f0'
down_revision: Union[str, Sequence[str], None] = 'f559570bf898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('rating', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'rating')
    # ### end Alembic commands ###
