"""Add throwing hand, batting hand, age to players; remove secondary position option from pitchers

Revision ID: d502126ee310
Revises: d64580871cb1
Create Date: 2026-07-06 16:39:46.256819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd502126ee310'
down_revision: Union[str, Sequence[str], None] = 'd64580871cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('players', sa.Column('throw_hand', sa.String(), nullable=True))
    op.add_column('players', sa.Column('bat_hand', sa.String(), nullable=True))
    op.add_column('players', sa.Column('age', sa.Integer(), nullable=True))

    connection = op.get_bind()
    connection.execute(sa.text(
        "UPDATE players SET throw_hand = 'R', bat_hand = 'R', age = 25 "
        "WHERE throw_hand IS NULL"
    ))

    # clean up any pitchers that had secondary positions under the old rules
    connection.execute(sa.text(
        "UPDATE players SET secondary_positions = NULL "
        "WHERE primary_position IN ('SP', 'RP', 'SP/RP', 'CP')"
    ))

    op.alter_column('players', 'throw_hand', nullable=False)
    op.alter_column('players', 'bat_hand', nullable=False)
    op.alter_column('players', 'age', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'age')
    op.drop_column('players', 'bat_hand')
    op.drop_column('players', 'throw_hand')
    # ### end Alembic commands ###
