"""make team abbreviation optional

Revision ID: d64580871cb1
Revises: e5b3d65014e2
Create Date: 2026-07-06 15:40:13.800420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64580871cb1'
down_revision: Union[str, Sequence[str], None] = 'e5b3d65014e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
