"""add_arm_slot_to_players

Revision ID: ea23537c51f9
Revises: 97fd064c0446
Create Date: 2026-08-16 00:01:20.973407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea23537c51f9'
down_revision: Union[str, Sequence[str], None] = '97fd064c0446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # replaced autogenerated alembic code, added manually
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'arm_slot')
    # ### end Alembic commands ###
